// Generated by CoffeeScript 1.10.0
var dgram;

dgram = require('dgram');

module.exports = {
  client: function(config) {
    var address, port, ref, ref1, udpClient, version;
    version = (config != null ? config.ipv6 : void 0) ? 'udp6' : 'udp4';
    port = (ref = config != null ? config.port : void 0) != null ? ref : 8125;
    address = (ref1 = config != null ? config.address : void 0) != null ? ref1 : void 0;
    udpClient = dgram.createSocket(version);
    return {
      send: function(message, cb) {
        var data;
        data = JSON.stringify(message);
        return udpClient.send(data, port, address, function(err) {
          return cb;
        });
      },
      close: function(cb) {
        return udpClient.close(cb);
      }
    };
  },
  server: function(config, cb) {
    var address, port, ref, ref1, udpServer, version;
    version = (config != null ? config.ipv6 : void 0) ? 'udp6' : 'udp4';
    port = (ref = config != null ? config.port : void 0) != null ? ref : 8125;
    address = (ref1 = config != null ? config.address : void 0) != null ? ref1 : void 0;
    udpServer = dgram.createSocket(version);
    udpServer.on('message', function(data, info) {
      var message;
      message = JSON.parse(data.toString());
      return cb(null, message, info);
    });
    udpServer.on('error', function(err) {
      return cb(err);
    });
    udpServer.bind(port, address);
    return {
      close: function(cb) {
        return udpServer.close(cb);
      }
    };
  }
};
